#Requires -Version 5.1
<#
  Installs this repo's shared AI config into ~/.claude, ~/.codex and ~/.agents.

  Directories are junctioned (live — edit the repo, every tool sees it).
  Files are copied (re-run this script after editing them in the repo).
  {{HOME}} inside copied files is replaced with this machine's home directory.
  Anything it would overwrite is backed up to ~/.claude/_preinstall-backup-<date>.
#>
[CmdletBinding()]
param([switch]$WhatIfOnly)

$ErrorActionPreference = 'Stop'
$repo      = $PSScriptRoot
$claudeDir = Join-Path $HOME '.claude'
$codexDir  = Join-Path $HOME '.codex'
$agentsDir = Join-Path $HOME '.agents'
$backup    = Join-Path $claudeDir ("_preinstall-backup-" + (Get-Date -Format 'yyyyMMdd-HHmmss'))
$homeFwd   = $HOME -replace '\\', '/'   # forward slashes work in bash, PowerShell and node

function Backup-Item2($path) {
    if (-not (Test-Path $path)) { return }
    if (-not (Test-Path $backup)) { New-Item -ItemType Directory -Path $backup -Force | Out-Null }
    Copy-Item $path (Join-Path $backup (Split-Path $path -Leaf)) -Recurse -Force
    Write-Host "  backed up $(Split-Path $path -Leaf)" -ForegroundColor DarkGray
}

# Copy a file, substituting {{HOME}}. Backs up any existing destination.
function Copy-Templated($src, $dst) {
    if ($WhatIfOnly) { Write-Host "  would copy $(Split-Path $src -Leaf) -> $dst"; return }
    Backup-Item2 $dst
    $content = (Get-Content $src -Raw) -replace '\{\{HOME\}\}', $homeFwd
    New-Item -ItemType Directory -Path (Split-Path $dst -Parent) -Force | Out-Null
    Set-Content -Path $dst -Value $content -Encoding UTF8 -NoNewline
    Write-Host "  $(Split-Path $dst -Leaf)" -ForegroundColor Green
}

# Junction $link -> $target. Real directories are backed up (or skipped if $skipReal).
function Set-Junction($link, $target, [switch]$skipReal) {
    $name = Split-Path $link -Leaf
    $item = Get-Item $link -ErrorAction SilentlyContinue
    if ($item -and ($item.LinkType -eq 'Junction' -or $item.LinkType -eq 'SymbolicLink')) {
        if ($WhatIfOnly) { Write-Host "  would relink $name"; return }
        Remove-Item $link -Force
    } elseif ($item) {
        if ($skipReal) { Write-Host "  SKIP $name - a real directory already exists there" -ForegroundColor Yellow; return }
        if ($WhatIfOnly) { Write-Host "  would BACK UP then replace real dir $name" -ForegroundColor Yellow; return }
        Backup-Item2 $link
        Remove-Item $link -Recurse -Force
    } elseif ($WhatIfOnly) { Write-Host "  would create $name"; return }
    New-Item -ItemType Junction -Path $link -Target $target | Out-Null
    Write-Host "  $name -> $target" -ForegroundColor Green
}

New-Item -ItemType Directory -Path $claudeDir, $codexDir, $agentsDir -Force | Out-Null

Write-Host "`nJunctioning shared directories into ~/.claude:" -ForegroundColor Cyan
foreach ($d in 'skills','commands','guidelines') {
    Set-Junction (Join-Path $claudeDir $d) (Join-Path $repo "shared\$d")
}

Write-Host "`nCopying Claude config files:" -ForegroundColor Cyan
foreach ($f in 'CLAUDE.md','ORCHESTRATION.md','settings.json','keybindings.json') {
    Copy-Templated (Join-Path $repo "claude\$f") (Join-Path $claudeDir $f)
}

Write-Host "`nCopying hook scripts:" -ForegroundColor Cyan
foreach ($h in Get-ChildItem (Join-Path $repo 'shared\hooks') -File) {
    Copy-Templated $h.FullName (Join-Path $claudeDir "hooks\$($h.Name)")
    Copy-Templated $h.FullName (Join-Path $codexDir  "hooks\$($h.Name)")
}

Write-Host "`nGenerating ~/.codex/AGENTS.md from shared/guidelines:" -ForegroundColor Cyan
$agents = Join-Path $codexDir 'AGENTS.md'
$parts  = Get-ChildItem (Join-Path $repo 'shared\guidelines') -Filter *.md | Sort-Object Name
if (-not $WhatIfOnly) {
    $out = "<!-- GENERATED by install.ps1 from shared/guidelines. Do not edit here. -->`n"
    foreach ($p in $parts) { $out += "`n" + (Get-Content $p.FullName -Raw).TrimEnd() + "`n" }
    Set-Content -Path $agents -Value $out -Encoding UTF8
}
Write-Host "  AGENTS.md ($($parts.Count) guideline files)" -ForegroundColor Green

Write-Host "`nMerging codex/hooks.json into ~/.codex/hooks.json:" -ForegroundColor Cyan
# Only the event keys present in the repo file are replaced; other events
# (e.g. a machine-local SessionStart hook) are preserved.
$codexHooksPath = Join-Path $codexDir 'hooks.json'
$repoHooks = ((Get-Content (Join-Path $repo 'codex\hooks.json') -Raw) -replace '\{\{HOME\}\}', $homeFwd) | ConvertFrom-Json
$live = if (Test-Path $codexHooksPath) { Get-Content $codexHooksPath -Raw | ConvertFrom-Json } else { [pscustomobject]@{ hooks = [pscustomobject]@{} } }
if (-not $live.hooks) { $live | Add-Member -NotePropertyName hooks -NotePropertyValue ([pscustomobject]@{}) }
foreach ($ev in $repoHooks.hooks.PSObject.Properties) {
    if ($live.hooks.PSObject.Properties[$ev.Name]) { $live.hooks.($ev.Name) = $ev.Value } else { $live.hooks | Add-Member -NotePropertyName $ev.Name -NotePropertyValue $ev.Value }
    Write-Host "  $($ev.Name)" -ForegroundColor Green
}
if (-not $WhatIfOnly) {
    Backup-Item2 $codexHooksPath
    $live | ConvertTo-Json -Depth 10 | Set-Content -Path $codexHooksPath -Encoding UTF8
}

Write-Host "`nJunctioning skills into ~/.codex/skills and ~/.agents/skills:" -ForegroundColor Cyan
foreach ($root in @((Join-Path $codexDir 'skills'), (Join-Path $agentsDir 'skills'))) {
    New-Item -ItemType Directory -Path $root -Force | Out-Null
    foreach ($sk in Get-ChildItem (Join-Path $repo 'shared\skills') -Directory) {
        Set-Junction (Join-Path $root $sk.Name) $sk.FullName -skipReal
    }
}

Write-Host "`nDone." -ForegroundColor Cyan
if (Test-Path $backup) { Write-Host "Backups: $backup" -ForegroundColor Yellow }
Write-Host @"

Manual steps remaining on this machine:
  1. Copy claude\settings.local.example.json to ~/.claude/settings.local.json and fill in paths.
  2. Apply codex\config.shared.toml keys to ~/.codex/config.toml by hand (it holds
     machine-specific [projects] and [marketplaces] state). [features] hooks = true is required.
  3. Install the public skills plugin (pr-brief, generate-pr-description) in Claude Code:
       /plugin marketplace add MichaelZhouNz/skills
       /plugin install mz-skills
     and for Codex / other tools:
       npx skills add MichaelZhouNz/skills
  4. Prerequisites on PATH: node, rtk, gh.
"@ -ForegroundColor Yellow
